// Auto-generates src/data/media.generated.ts by scanning public/.
// Runs as the `prebuild` npm hook so <Media> always resolves real assets.
// Pure data output (a string array + helper), safe to bundle in client and server.

import { readdirSync, statSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = join(process.cwd(), "public");
if (!existsSync(root)) {
  console.warn("[gen-media] no public/ folder found, writing empty manifest");
}

const files = [];

function walk(dir) {
  let entries = [];
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (entry.isFile()) {
      const rel = relative(root, full).split(sep).join("/");
      files.push(rel);
    }
  }
}
walk(root);
files.sort();

const body = `// AUTO-GENERATED by scripts/gen-media.mjs. Do not edit by hand.
// Lists every file under public/ so <Media> can resolve real assets at build time.
// Kept as plain data so it bundles cleanly in both server and client components.

export const MEDIA_FILES = ${JSON.stringify(files, null, 2)} as const;

const SET: ReadonlySet<string> = new Set(MEDIA_FILES);

// path is the public-relative path, with or without a leading slash.
export function hasMedia(path: string): boolean {
  return SET.has(path.replace(/^\\//, ""));
}
`;

mkdirSync(join(process.cwd(), "src", "data"), { recursive: true });
writeFileSync(join(process.cwd(), "src", "data", "media.generated.ts"), body);
console.log(`[gen-media] wrote ${files.length} files to src/data/media.generated.ts`);
