// AUTO-GENERATED by scripts/gen-media.mjs. Do not edit by hand.
// Lists every file under public/ so <Media> can resolve real assets at build time.
// Kept as plain data so it bundles cleanly in both server and client components.

export const MEDIA_FILES = [
  "img/whatsapp.png",
  "manifest.json",
  "video/README.md"
] as const;

const SET: ReadonlySet<string> = new Set(MEDIA_FILES);

// path is the public-relative path, with or without a leading slash.
export function hasMedia(path: string): boolean {
  return SET.has(path.replace(/^\//, ""));
}
